twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        site_name: 'Mon application'
        pitch: 'Une application totalement inutile mais super cool'
    form_themes: ['bootstrap_4_layout.html.twig']

when@test:
    twig:
        strict_variables: true
